hydra:
  run:
    dir: outputs/qa_inference/${dataset.data_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - doc_ranker: idf_topk_ranker
  - qa_prompt: 2wikimultihopqa
  - qa_evaluator: 2wikimultihopqa

seed: 1024

dataset:
  root: ./data
  data_name: 2wikimultihopqa_test

llm:
  _target_: gfmrag.llms.Ollama
  model_name: mistral
  maximum_token: 4096
  retry: 5

graph_retriever:
  model_path: rmanluo/GFM-RAG-8M

test:
  retrieval_batch_size: 8
  top_k: 5
  save_retrieval: False
  save_top_k_entity: 10
  n_threads: 5
  retrieved_result_path: null
  prediction_result_path: null
  init_entities_weight: True
